networks:
  mcp-time-server-network:
    driver: bridge
    name: mcp-time-server-network

services:

  mcp-time-server:
    container_name: mcp-time-server
    restart: unless-stopped
    image: ghcr.io/tombenke/mcp-time-server:latest
    ports:
      - 8080:8080
    networks:
      mcp-time-server-network:
        aliases:
          - mcp-time-server
